#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII
bspc monitor DP1 -d VIII IX X
bspc config border_width        3
bspc config normal_border_color "#9CC57E"
bspc config active_border_color "#9CC57E"
bspc config focused_border_color "#9CC57E"
bspc config urgent_border_color "#9CC57E"
bspc config presel_border_color "#9CC57E"

# bspc rule -a Termite border_width=10

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer true


~/.fehbg &

$HOME/.config/polybar/launch.sh &

compton -b --config /home/chromze/.config/compton/compton.conf &
